import csv


def get_symptom_probability_distribution():
    with open(
        "csv/Training Data Symptom Probability Distribution Table.csv",
        newline="",
    ) as csv_file:
        reader = csv.DictReader(csv_file)
        symptoms = []
        for row in reader:
            symptoms.append(
                [
                    row["Symptom"],
                    row["Probability"],
                    row["Not-Symptom"],
                    row["Not-Probability"],
                ]
            )
        return symptoms


def get_disease_partial_conditional_probability_distribution():
    with open(
        "csv/Training Data Disease Conditional Probabilty Table.csv",
        newline="",
    ) as csv_file:
        reader = csv.DictReader(csv_file)
        diseases = []
        for row in reader:
            diseases.append(
                [
                    row["itching"],
                    row["skin_rash"],
                    row["nodal_skin_eruptions"],
                    row["continuous_sneezing"],
                    row["shivering"],
                    row["chills"],
                    row["joint_pain"],
                    row["stomach_pain"],
                    row["acidity"],
                    row["ulcers_on_tongue"],
                    row["muscle_wasting"],
                    row["vomiting"],
                    row["burning_micturition"],
                    row["spotting_ urination"],
                    row["fatigue"],
                    row["weight_gain"],
                    row["anxiety"],
                    row["cold_hands_and_feets"],
                    row["mood_swings"],
                    row["weight_loss"],
                    row["restlessness"],
                    row["lethargy"],
                    row["patches_in_throat"],
                    row["irregular_sugar_level"],
                    row["cough"],
                    row["high_fever"],
                    row["sunken_eyes"],
                    row["breathlessness"],
                    row["sweating"],
                    row["dehydration"],
                    row["indigestion"],
                    row["headache"],
                    row["yellowish_skin"],
                    row["dark_urine"],
                    row["nausea"],
                    row["loss_of_appetite"],
                    row["pain_behind_the_eyes"],
                    row["back_pain"],
                    row["constipation"],
                    row["abdominal_pain"],
                    row["diarrhoea"],
                    row["mild_fever"],
                    row["yellow_urine"],
                    row["yellowing_of_eyes"],
                    row["acute_liver_failure"],
                    row["fluid_overload"],
                    row["swelling_of_stomach"],
                    row["swelled_lymph_nodes"],
                    row["malaise"],
                    row["blurred_and_distorted_vision"],
                    row["phlegm"],
                    row["throat_irritation"],
                    row["redness_of_eyes"],
                    row["sinus_pressure"],
                    row["runny_nose"],
                    row["congestion"],
                    row["chest_pain"],
                    row["weakness_in_limbs"],
                    row["fast_heart_rate"],
                    row["pain_during_bowel_movements"],
                    row["pain_in_anal_region"],
                    row["bloody_stool"],
                    row["irritation_in_anus"],
                    row["neck_pain"],
                    row["dizziness"],
                    row["cramps"],
                    row["bruising"],
                    row["obesity"],
                    row["swollen_legs"],
                    row["swollen_blood_vessels"],
                    row["puffy_face_and_eyes"],
                    row["enlarged_thyroid"],
                    row["brittle_nails"],
                    row["swollen_extremeties"],
                    row["excessive_hunger"],
                    row["extra_marital_contacts"],
                    row["drying_and_tingling_lips"],
                    row["slurred_speech"],
                    row["knee_pain"],
                    row["hip_joint_pain"],
                    row["muscle_weakness"],
                    row["stiff_neck"],
                    row["swelling_joints"],
                    row["movement_stiffness"],
                    row["spinning_movements"],
                    row["loss_of_balance"],
                    row["unsteadiness"],
                    row["weakness_of_one_body_side"],
                    row["loss_of_smell"],
                    row["bladder_discomfort"],
                    row["foul_smell_of urine"],
                    row["continuous_feel_of_urine"],
                    row["passage_of_gases"],
                    row["internal_itching"],
                    row["toxic_look_(typhos)"],
                    row["depression"],
                    row["irritability"],
                    row["muscle_pain"],
                    row["altered_sensorium"],
                    row["red_spots_over_body"],
                    row["belly_pain"],
                    row["abnormal_menstruation"],
                    row["dischromic _patches"],
                    row["watering_from_eyes"],
                    row["increased_appetite"],
                    row["polyuria"],
                    row["family_history"],
                    row["mucoid_sputum"],
                    row["rusty_sputum"],
                    row["lack_of_concentration"],
                    row["visual_disturbances"],
                    row["receiving_blood_transfusion"],
                    row["receiving_unsterile_injections"],
                    row["coma"],
                    row["stomach_bleeding"],
                    row["distention_of_abdomen"],
                    row["history_of_alcohol_consumption"],
                    row["fluid_overload"],
                    row["blood_in_sputum"],
                    row["prominent_veins_on_calf"],
                    row["palpitations"],
                    row["painful_walking"],
                    row["pus_filled_pimples"],
                    row["blackheads"],
                    row["skin_peeling"],
                    row["scurring"],
                    row["silver_like_dusting"],
                    row["small_dents_in_nails"],
                    row["inflammatory_nails"],
                    row["blister"],
                    row["red_sore_around_nose"],
                    row["yellow_crust_ooze"],
                    row["prognosis"],
                    row["Disease Probability"],
                ]
            )
        return diseases
